permalink: /:title/
url: http://xiaoqshou.com
name: xiaoqshou.com
author: AoGang
qq: 43938831
email: xiaoqshou@gmail.com
duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959
github: xiaoqshou
pygments: true
safe: true
paginate: 20
about: "xiaoqshou"
