markdown: rdiscount
permalink: /:title/
url: :
name: xiaoqshou.com 
author: Young
qq: 43938831
email: xiaoqshou@gmail.com
duoshuo: 
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: xiaoqshou
pygments: true
safe: true
paginate: 20
about: "xiaoqshou"
