markdown: rdiscount
permalink: /:title/
url: 
name: YoungLiou
author: xiaoqshou
qq: 43938831
email: xiaoqshou@gmail.com
duoshuo: yonsm
beian: 浙ICP备12026616号
cnzz: 119959
weibo: 1885061391
github: xiaoqshou
pygments: true
safe: true
paginate: 20
about: "xiaoqshou's blog.so.. have fun..."
