permalink: /:title/
url: http://xiaoqshou.com
name: 89Ao.info
author: AoGang
qq: 103230005
email: 89ao@live.com
duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: xiaoqshou
pygments: true
safe: true
paginate: 20
about: "xiaoqshou"
