permalink: /:title/
url: http://xiaoqshou.com
name: xiaoqshou.Info
author: Young
qq: 43938831 
email: xiaoqshou@gmail.com
duoshuo: xiaoqshou
#beian: 浙ICP备12026616号
#cnzz: 119959
github: xiaoqshou
pygments: true
safe: true
paginate: 20
about: "xiaoqshou"
